# Generated by Django 5.1.2 on 2024-12-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsrequestorder',
            name='department',
            field=models.CharField(blank=True, choices=[('', ''), ('Engineering', 'Engineering'), ('Technology', 'Technology'), ('Operations', 'Operations'), ('Planning', 'Planning'), ('Information Technology', 'Information Technology'), ('Customer Support', 'Customer Support'), ('Research & Development', 'Research & Development'), ('Legal & Compliance', 'Legal & Compliance'), ('SCM', 'Supply Chain Management (SCM)'), ('Logistics', 'Logistics'), ('Quality Assurance', 'Quality Assurance'), ('Business Control', 'Business Control'), ('Design and Creative', 'Design and Creative'), ('Public Relations', 'Public Relations'), ('Corporate Strategy and Planning', 'Corporate Strategy and Planning'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Finance', 'Finance'), ('Accounting', 'Accounting'), ('Production', 'Production'), ('Admin', 'Admin'), ('HR', 'Human Resources'), ('Training and Development', 'Training and Development'), ('Event Management', 'Event Management'), ('Environmental, Social, and Governance (ESG)', 'Environmental, Social, and Governance (ESG)'), ('Health and Safety', 'Health and Safety'), ('Business Development', 'Business Development'), ('Facilities Management', 'Facilities Management'), ('Investor Relations', 'Investor Relations'), ('Medical Healthcare', 'Medical Healthcare'), ('Procurement', 'Procurement'), ('Security', 'Security'), ('Learning and Development', 'Learning and Development'), ('Corporate Communications', 'Corporate Communications'), ('Sustainability', 'Sustainability')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalMaterialsRequestOrder',
        ),
    ]
