# Generated by Django 5.1.2 on 2024-11-18 04:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_historicalinventorytransaction_remarks_and_more'),
        ('manufacture', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialsdeliveryorderitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='materialsdeliveryorderitem',
            name='materials_request_order',
        ),
        migrations.RemoveField(
            model_name='materialsdeliveryorderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='materialsdeliveryorderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='materialsdeliveryorderitem',
            name='warehouse',
        ),
        migrations.AlterModelOptions(
            name='materialsrequestorder',
            options={'permissions': [('can_request', 'can request'), ('can_review', 'Can review'), ('can_approve', 'Can approve')]},
        ),
        migrations.RenameField(
            model_name='historicalmaterialsrequestitem',
            old_name='material_request_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='historicalqualitycontrol',
            old_name='quantity_received',
            new_name='bad_quantity',
        ),
        migrations.RenameField(
            model_name='historicalreceivefinishedgoods',
            old_name='receive_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='materialsrequestitem',
            old_name='material_request_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='qualitycontrol',
            old_name='quantity_received',
            new_name='bad_quantity',
        ),
        migrations.RenameField(
            model_name='receivefinishedgoods',
            old_name='receive_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='finishedgoodsreadyfromproduction',
            name='quality_check_passed',
        ),
        migrations.RemoveField(
            model_name='historicalfinishedgoodsreadyfromproduction',
            name='quality_check_passed',
        ),
        migrations.RemoveField(
            model_name='historicalqualitycontrol',
            name='qc_id',
        ),
        migrations.RemoveField(
            model_name='historicalqualitycontrol',
            name='result',
        ),
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='qc_id',
        ),
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='result',
        ),
        migrations.AddField(
            model_name='finishedgoodsreadyfromproduction',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalfinishedgoodsreadyfromproduction',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialsrequestitem',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialsrequestorder',
            name='Approver_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialsrequestorder',
            name='Requester_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialsrequestorder',
            name='Reviewer_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialsrequestorder',
            name='approval_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialsrequestorder',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialsrequestorder',
            name='approver_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialsrequestorder',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialsrequestorder',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialsrequestorder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialsrequestorder',
            name='requester_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialsrequestorder',
            name='reviewer_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialsrequestorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalqualitycontrol',
            name='total_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialsrequestitem',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='materialsrequestorder',
            name='Approver_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialsrequestorder',
            name='Requester_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialsrequestorder',
            name='Reviewer_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialsrequestorder',
            name='approval_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='materialsrequestorder',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='materialsrequestorder',
            name='approver_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='materialsrequestorder',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materialsrequestorder',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialsrequestorder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialsrequestorder',
            name='requester_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='materialsrequestorder',
            name='reviewer_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='materialsrequestorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='total_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterialsrequestorder',
            name='created_at',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalmaterialsrequestorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterialsrequestorder',
            name='status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Created'), ('IN_PROCESS', 'In Process'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='materialsrequestorder',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='materialsrequestorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materialsrequestorder',
            name='status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Created'), ('IN_PROCESS', 'In Process'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='qualitycontrol',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.CreateModel(
            name='HistoricalMaterialsDeliveryItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('item_id', models.CharField(max_length=20)),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('COMPONENT', 'Component')], max_length=10)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location')),
                ('materials_request_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manufacture.materialsrequestitem')),
                ('materials_request_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manufacture.materialsrequestorder')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'historical materials delivery item',
                'verbose_name_plural': 'historical materials delivery items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MaterialsDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=20)),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('COMPONENT', 'Component')], max_length=10)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
                ('materials_request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials_request_items', to='manufacture.materialsrequestitem')),
                ('materials_request_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials_request_delivery', to='manufacture.materialsrequestorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_item_for_delivery', to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalMaterialsDeliveryOrderItem',
        ),
        migrations.DeleteModel(
            name='MaterialsDeliveryOrderItem',
        ),
    ]
