# Generated by Django 5.1.2 on 2024-11-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0002_remove_materialsdeliveryorderitem_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaterialsdeliveryitem',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialsrequestitem',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='materialsdeliveryitem',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='materialsrequestitem',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
