# Generated by Django 5.1.2 on 2024-12-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0002_alter_materialsrequestorder_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedgoodsreadyfromproduction',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('DELIVERED', 'Delivered'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
    ]
