# Generated by Django 5.1.2 on 2024-11-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0003_historicalmaterialsdeliveryitem_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedgoodsreadyfromproduction',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalfinishedgoodsreadyfromproduction',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
