# Generated by Django 5.1.2 on 2024-12-15 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0003_alter_finishedgoodsreadyfromproduction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedgoodsreadyfromproduction',
            name='materials_request_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture.materialsrequestorder'),
        ),
    ]
