# Generated by Django 5.1.2 on 2024-11-18 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0004_alter_finishedgoodsreadyfromproduction_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycontrol',
            name='finish_goods_from_production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_quality', to='manufacture.finishedgoodsreadyfromproduction'),
        ),
    ]
