# Generated by Django 5.1.2 on 2024-11-18 13:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0005_alter_qualitycontrol_finish_goods_from_production'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalQualityControl',
            new_name='HistoricalManufactureQualityControl',
        ),
        migrations.RenameModel(
            old_name='QualityControl',
            new_name='ManufactureQualityControl',
        ),
        migrations.AlterModelOptions(
            name='historicalmanufacturequalitycontrol',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical manufacture quality control', 'verbose_name_plural': 'historical manufacture quality controls'},
        ),
    ]
