# Generated by Django 5.1.2 on 2024-11-19 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0006_rename_historicalqualitycontrol_historicalmanufacturequalitycontrol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivefinishedgoods',
            name='quality_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_received', to='manufacture.manufacturequalitycontrol'),
        ),
    ]
