# Generated by Django 5.1.2 on 2024-11-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_initial'),
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedispatchitem',
            name='dispatch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_dispatch', to='purchase.purchaseorderitem'),
        ),
    ]
