# Generated by Django 5.1.2 on 2024-11-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_purchasedispatchitem_dispatch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedispatchitem',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('ON_BOARD', 'On Board'), ('IN_TRANSIT', 'In Transit'), ('REACHED', 'Reached'), ('CUSTOM_CLEARANCE_IN_PROCESS', 'Custom Clearance In Process'), ('DELIVERED', 'Delivered'), ('OBI', 'OBI'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROCESS', max_length=30, null=True),
        ),
    ]
