# Generated by Django 5.1.2 on 2024-11-10 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_alter_purchasedispatchitem_status'),
        ('sales', '0002_rename_sale_order_item_historicalsalequalitycontrol_sale_dispatch_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saledispatchschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='saledispatchschedule',
            name='dispatched_by',
        ),
        migrations.RemoveField(
            model_name='saledispatchschedule',
            name='sale_shipment',
        ),
        migrations.RemoveField(
            model_name='saledispatchschedule',
            name='user',
        ),
        migrations.AlterField(
            model_name='saleshipment',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_shipment', to='sales.saleorder'),
        ),
        migrations.CreateModel(
            name='SaleDispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_id', models.CharField(blank=True, max_length=20, null=True)),
                ('dispatch_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('ON_BOARD', 'On Board'), ('IN_TRANSIT', 'In Transit'), ('REACHED', 'Reached'), ('CUSTOM_CLEARANCE_IN_PROCESS', 'Custom Clearance In Process'), ('DELIVERED', 'Delivered'), ('OBI', 'OBI done'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROCESS', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_dispatch_item', to='sales.saleorderitem')),
                ('sale_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_shipment_dispatch', to='logistics.saleshipment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalSaleDispatchSchedule',
        ),
        migrations.DeleteModel(
            name='SaleDispatchSchedule',
        ),
    ]
