# Generated by Django 5.1.2 on 2024-11-11 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_saledispatchschedule_unique_together_and_more'),
        ('sales', '0002_rename_sale_order_item_historicalsalequalitycontrol_sale_dispatch_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleshipment',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_shipment', to='sales.saleorder'),
        ),
    ]
