# Generated by Django 5.1.2 on 2024-11-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_inventory_transaction'),
        ('logistics', '0008_alter_saleshipment_sales_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledispatchitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_location', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='saledispatchitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_warehouse', to='inventory.warehouse'),
        ),
    ]
