# Generated by Django 5.1.2 on 2024-11-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_saledispatchitem_location_saledispatchitem_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedispatchitem',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('ON_BOARD', 'On Board'), ('IN_TRANSIT', 'In Transit'), ('REACHED', 'Reached'), ('CUSTOM_CLEARANCE_IN_PROCESS', 'Custom Clearance In Process'), ('OBI', 'OBI done'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='IN_PROCESS', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='saledispatchitem',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('ON_BOARD', 'On Board'), ('IN_TRANSIT', 'In Transit'), ('REACHED', 'Reached'), ('CUSTOM_CLEARANCE_IN_PROCESS', 'Custom Clearance In Process'), ('OBI', 'OBI done'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='IN_PROCESS', max_length=30, null=True),
        ),
    ]
