# Generated by Django 5.1.2 on 2024-11-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_alter_purchasedispatchitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledispatchitem',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='IN_PROCESS', max_length=30, null=True),
        ),
    ]
