# Generated by Django 5.1.2 on 2024-11-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_alter_saledispatchitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseshipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROCESS', 'In Process'), ('IN_TRANSIT', 'In Transit'), ('REACHED', 'REACHED'), ('DELIVERED', 'Delivered'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseshipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROCESS', 'In Process'), ('IN_TRANSIT', 'In Transit'), ('REACHED', 'REACHED'), ('DELIVERED', 'Delivered'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
