# Generated by Django 5.1.2 on 2024-12-13 09:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('notice_attachment', models.ImageField(blank=True, null=True, upload_to='notices')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, default='None', max_length=100, null=True, unique=True)),
                ('name', models.CharField(blank=True, default='Nome', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, default='Nome', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='Nome', max_length=100, null=True)),
                ('posting_area', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Chittagong', 'Chittagong')], max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Nome', max_length=20, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('resignation_date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Format: YYYY-MM-DD', null=True)),
                ('position', models.CharField(blank=True, choices=[('Chairman', 'Chairman'), ('MD', 'MD'), ('CEO', 'CEO'), ('CFO', 'CFO'), ('CMO', 'CMO'), ('CTO', 'CTO'), ('Specialist', 'Specialist'), ('Manager', 'Manager'), ('Sr.Manager', 'Sr.Manager'), ('DGM', 'DGM'), ('GM', 'GM'), ('SrGM', 'SrGM'), ('Director', 'Director'), ('HOD', 'HOD'), ('Specialist', 'Specialist'), ('HSS_manager', 'HSS_manager'), ('Driver', 'Driver'), ('Peon', 'Peon'), ('General staff', 'General staff')], default='Nome', max_length=100, null=True)),
                ('department', models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Marketting', 'Marketing'), ('Finance', 'Finance'), ('Accounting', 'Accounting'), ('Technology', 'Technology'), ('Admin', 'Admin'), ('HR', 'HR'), ('Business_Development', 'Business_Development')], default='Nome', max_length=100, null=True)),
                ('employe_level', models.CharField(blank=True, choices=[('SeniorManagement', 'SeniorManagement'), ('MidLevelManager', 'MidLevelManager'), ('FirstLevelmanager', 'FirstLevelManager'), ('Executive', 'Executive'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Specialist', 'Specialist'), ('Officer', 'Officer'), ('FieldForce', 'FieldForce'), ('General_Staffs', 'General_Staffs')], default='executive', max_length=100, null=True)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('house_allowance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('medical_allowance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('transportation_allowance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overtime_pay_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('employee_photo_ID', models.ImageField(blank=True, null=True, upload_to='employee_photo_ID/')),
                ('gross_monthly_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_user', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_hq_user', to=settings.AUTH_USER_MODEL)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hq_employee_name', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('attendance_status', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], default='None', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRecordChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('field_name', models.CharField(default='None', max_length=100)),
                ('old_value', models.CharField(default='None', max_length=255)),
                ('new_value', models.CharField(default='None', max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_locations', to='core.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_location_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySalaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
    ]
