# Generated by Django 5.1.2 on 2024-11-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='notice_image',
            new_name='notice_attachment',
        ),
    ]
