# Generated by Django 5.1.2 on 2024-12-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_employee_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
