# Generated by Django 5.1.2 on 2024-12-27 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_salaryincrementandpromotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryincrementandpromotion',
            old_name='increment_section',
            new_name='increment_category',
        ),
    ]
