# Generated by Django 5.1.2 on 2024-12-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_given_promotion_recommendation_salaryincrementandpromotion_promotion_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='increment_category',
            field=models.CharField(blank=True, choices=[('BY_EMPLOYEE', 'By Employee'), ('BY_DEPARTMENT', 'By department'), ('BY_COMPANY', 'By Company')], default='BY_EMPLOYEE', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='increment_type',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half Yearly'), ('YEARLY', 'Yearly')], default='YEARLY', max_length=30, null=True),
        ),
    ]
