# Generated by Django 5.1.2 on 2024-12-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_salaryincrementandpromotion_increment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='increment_percentage',
            field=models.FloatField(blank=True, help_text='Enter  percentage of basic salary', null=True),
        ),
    ]
