# Generated by Django 5.1.2 on 2024-12-27 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_salaryincrementandpromotion_increment_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='increment_position', to='core.position'),
        ),
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='increment_employee', to='core.employee'),
        ),
    ]
