# Generated by Django 5.1.2 on 2024-12-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_salaryincrementandpromotion_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='increment_category',
            field=models.CharField(blank=True, choices=[('BY_EMPLOYEE', 'By Employee'), ('BY_DEPARTMENT', 'By department'), ('BY_POSITION', 'By Position'), ('BY_COMPANY', 'By Company')], default='BY_EMPLOYEE', max_length=30, null=True),
        ),
    ]
