# Generated by Django 5.1.2 on 2024-12-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_salaryincrementandpromotion_increment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='effective_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
