# Generated by Django 5.1.2 on 2024-12-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_employee_company_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
