# Generated by Django 5.1.2 on 2024-12-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_salaryincrementandpromotion_effective_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='increment_category',
            field=models.CharField(blank=True, choices=[('BY_EMPLOYEE', 'By Employee'), ('BY_DEPARTMENT', 'By department'), ('BY_POSITION', 'By Position'), ('BY_COMPANY', 'By Company')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='increment_type',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half Yearly'), ('YEARLY', 'Yearly')], max_length=30, null=True),
        ),
    ]
