# Generated by Django 5.1.2 on 2024-12-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_salaryincrementandpromotion_increment_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryincrementandpromotion',
            old_name='new_salary',
            new_name='new_basic_salary',
        ),
        migrations.RenameField(
            model_name='salaryincrementandpromotion',
            old_name='increment_percentage',
            new_name='promotional_increment_percentage',
        ),
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='salary_increment_percentage',
            field=models.FloatField(blank=True, help_text='Enter  percentage of basic salary', null=True),
        ),
    ]
