# Generated by Django 5.1.2 on 2024-12-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_new_salary_salaryincrementandpromotion_new_basic_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='promotional_increment_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='salary_increment_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
