# Generated by Django 5.1.2 on 2025-01-01 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_salaryincrementandpromotion_promotional_increment_percentage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salaryincrementandpromotion',
            unique_together={('employee', 'increment_type', 'increment_year')},
        ),
    ]
