# Generated by Django 5.1.2 on 2025-01-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_salaryincrementandpromotion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='avg_task_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='task_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='weight_final_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
