# Generated by Django 5.1.2 on 2025-01-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_salaryincrementandpromotion_avg_task_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryincrementandpromotion',
            name='weight_final_score',
        ),
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='weighted_final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='avg_task_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='task_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
