# Generated by Django 5.1.2 on 2025-01-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_salaryincrementandpromotion_weight_final_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='task_count_employee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
