# Generated by Django 5.1.2 on 2025-01-01 10:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_salaryincrementandpromotion_task_count_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='max_weighted_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='normalized_weighted_final_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True),
        ),
    ]
