# Generated by Django 5.1.2 on 2025-01-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_salaryincrementandpromotion_max_weighted_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryincrementandpromotion',
            old_name='task_count',
            new_name='max_task_count',
        ),
    ]
