# Generated by Django 5.1.2 on 2025-01-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_task_count_salaryincrementandpromotion_max_task_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryincrementandpromotion',
            name='max_weighted_score',
        ),
        migrations.RemoveField(
            model_name='salaryincrementandpromotion',
            name='normalized_weighted_final_score',
        ),
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='task_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
