# Generated by Django 5.1.2 on 2025-01-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_salaryincrementandpromotion_task_factor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryincrementandpromotion',
            old_name='increment_category',
            new_name='appraisal_category',
        ),
        migrations.RenameField(
            model_name='salaryincrementandpromotion',
            old_name='increment_type',
            new_name='appraisal_type',
        ),
        migrations.RenameField(
            model_name='salaryincrementandpromotion',
            old_name='increment_year',
            new_name='appraisal_year',
        ),
        migrations.AlterUniqueTogether(
            name='salaryincrementandpromotion',
            unique_together={('employee', 'appraisal_type', 'appraisal_year')},
        ),
    ]
