# Generated by Django 5.1.2 on 2025-01-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_increment_category_salaryincrementandpromotion_appraisal_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='appraisal_type',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF-YEARLY', 'Half Yearly'), ('YEARLY', 'Yearly')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='half_year',
            field=models.CharField(blank=True, choices=[('1ST-HALF-YEAR', 'First Half Year'), ('2ND-HALF-YEAR', 'Second Half Year')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='quarter',
            field=models.CharField(blank=True, choices=[('1ST-QUARTER', '1st Quarter'), ('2ND-QUARTER', '2nd Quarter'), ('3RD_QUARTER', '3rd Quarter'), ('4TH-QUARTER', '4th Quarter')], max_length=30, null=True),
        ),
    ]
