# Generated by Django 5.1.2 on 2025-01-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_salaryincrementandpromotion_appraisal_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryincrementandpromotion',
            old_name='increment_amount',
            new_name='obtained_promotional_increment_percentage',
        ),
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='obtained_salary_increment_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='promotional_increment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='salary_increment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
