# Generated by Django 5.1.2 on 2025-01-22 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_employee_basic_salary_remove_employee_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarystructure',
            name='income_tax_rate',
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
