# Generated by Django 5.1.2 on 2025-01-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_salarystructure_income_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystructure',
            name='salary_structure_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
