# Generated by Django 5.1.2 on 2025-01-22 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_companypolicy_user_salarystructure_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystructure',
            name='company_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.companypolicy'),
        ),
    ]
