# Generated by Django 5.1.2 on 2025-01-22 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_salarystructure_company_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypolicy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='policy_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base salary of the employee', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='salary_level',
            field=models.CharField(blank=True, choices=[('LEVEL-1', 'Level-1'), ('LEVEL2', 'Level-2'), ('LEVEL-3', 'Level-3'), ('LEVEL-4', 'Level-4'), ('LEVEL-5', 'Level-5'), ('LEVEL-6', 'Level-6'), ('LEVEL-7', 'Level-7'), ('LEVEL-8', 'Level-8'), ('LEVEL-9', 'Level-9'), ('LEVEL-10', 'Level-10')], max_length=50, null=True),
        ),
    ]
