# Generated by Django 5.1.2 on 2025-01-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_companypolicy_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystructure',
            name='car_entitle_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Entitled to a car?'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='food_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Allowance for meals or food', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='income_tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Income tax deduction', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='insurance',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cover insurance policy?'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='overtime_pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Rate per hour for overtime work', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='stock_options',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='have stock option?'),
        ),
    ]
