# Generated by Django 5.1.2 on 2025-01-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_salarystructure_car_entitle_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypolicy',
            name='conveyance_allowance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='festival_bonus_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='grauity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=12.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='hra_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=40.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='leave_travel_allowance_performance',
            field=models.DecimalField(blank=True, decimal_places=2, default=12.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='medical_allowance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='performance_bonus_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=5.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='professional_tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='provident_fund_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=12.0, max_digits=5, null=True),
        ),
    ]
