# Generated by Django 5.1.2 on 2025-01-23 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_companypolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gross_monthly_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='house_allowance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='medical_allowance',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='overtime_pay_rate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='transportation_allowance',
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('salary_structure_code', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_level', models.CharField(blank=True, choices=[('LEVEL-1', 'Level-1'), ('LEVEL2', 'Level-2'), ('LEVEL-3', 'Level-3'), ('LEVEL-4', 'Level-4'), ('LEVEL-5', 'Level-5'), ('LEVEL-6', 'Level-6'), ('LEVEL-7', 'Level-7'), ('LEVEL-8', 'Level-8'), ('LEVEL-9', 'Level-9'), ('LEVEL-10', 'Level-10')], max_length=50, null=True)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Base salary of the employee', max_digits=15, null=True)),
                ('car_entitle_status', models.BooleanField(blank=True, default=False, null=True, verbose_name='Entitled to a car?')),
                ('food_allowance', models.DecimalField(blank=True, decimal_places=2, help_text='Allowance for meals or food', max_digits=10, null=True)),
                ('insurance', models.BooleanField(blank=True, default=False, null=True, verbose_name='Cover insurance policy?')),
                ('stock_options', models.BooleanField(blank=True, default=False, null=True, verbose_name='have stock option?')),
                ('overtime_pay_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Rate per hour for overtime work', max_digits=10, null=True)),
                ('income_tax_percentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Income tax deduction', max_digits=10, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.companypolicy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
