# Generated by Django 5.1.2 on 2025-01-23 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_employee_basic_salary_remove_employee_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='incremental_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='promotion_status',
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_structure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.salarystructure'),
        ),
    ]
