# Generated by Django 5.1.2 on 2025-01-23 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_employee_incremental_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.salarystructure'),
        ),
    ]
