# Generated by Django 5.1.2 on 2025-01-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_employee_salary_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='any name you prefer', max_length=50, null=True)),
                ('month', models.PositiveIntegerField(help_text='use numerical month like 1,2 etc. 1=January, 2=February')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companypolicy')),
            ],
        ),
        migrations.CreateModel(
            name='PeformanceBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='any name you prefer', max_length=50, null=True)),
                ('month', models.PositiveIntegerField(help_text='use numerical month like 1=January, 2=February')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companypolicy')),
            ],
        ),
    ]
