# Generated by Django 5.1.2 on 2025-01-24 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_festival_user_performancebonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliciesAndGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace_security_policies', models.ImageField(blank=True, null=True, upload_to='workplace_security_policies')),
                ('workplace_health_safety', models.ImageField(blank=True, null=True, upload_to='workplace_health_safety')),
                ('equal_opportunity_policy', models.ImageField(blank=True, null=True, upload_to='equal_opportunity_policy')),
                ('employee_code_of_conduct_policy', models.ImageField(blank=True, null=True, upload_to='employee_code_of_conduct_policy ')),
                ('leave_of_absence_policy', models.ImageField(blank=True, null=True, upload_to='leave_of_absence_policy')),
                ('employee_disciplinary_action_policy', models.ImageField(blank=True, null=True, upload_to='employee_disciplinary_action_policy')),
                ('travel_policies', models.ImageField(blank=True, null=True, upload_to='travel_policies')),
                ('remote_work_policy', models.ImageField(blank=True, null=True, upload_to=' remote_work_policy')),
                ('work_schedule_and_rest_period_policies', models.ImageField(blank=True, null=True, upload_to='work_schedule_and_rest_period_policies')),
                ('ethics_policy', models.ImageField(blank=True, null=True, upload_to='ethics_policy')),
                ('employee_complaint_policies', models.ImageField(blank=True, null=True, upload_to='employee_complaint_policies')),
                ('compensation_and_benefits_policy', models.ImageField(blank=True, null=True, upload_to='compensation_and_benefits_policy')),
                ('employee_fraternization_policy', models.ImageField(blank=True, null=True, upload_to='employee_fraternization_policy')),
                ('BYOD', models.ImageField(blank=True, null=True, upload_to='BYOD')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
    ]
