# Generated by Django 5.1.2 on 2025-01-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_policiesandguideline'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
