# Generated by Django 5.1.2 on 2025-01-31 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_company_email_company_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employe_level',
        ),
        migrations.AddField(
            model_name='position',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Employeelevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('', ''), ('Executive Leadership', 'Executive Leadership'), ('Senior Management', 'Senior Management'), ('Middle Management', 'Middle Management'), ('First-Line Management', 'First-Line Management'), ('Executive', 'Executive'), ('Senior Engineer', 'Senior Engineer'), ('Engineer', 'Engineer'), ('Junior Engineer', 'Junior Engineer'), ('Doctor', 'Doctor'), ('Specialist', 'Specialist'), ('Officer', 'Officer'), ('Field Force', 'Field Force'), ('General Staff', 'General Staff'), ('Intern', 'Intern'), ('Consultant', 'Consultant'), ('Technician', 'Technician'), ('Supervisor', 'Supervisor'), ('Associate', 'Associate')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='employee_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_level', to='core.employeelevel'),
        ),
    ]
