# Generated by Django 5.1.2 on 2025-02-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_employee_employe_level_position_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_NID',
            field=models.ImageField(blank=True, help_text='pls upload single image file', null=True, upload_to='employee_nid/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_education_certificate',
            field=models.ImageField(blank=True, help_text='pls upload single image file', null=True, upload_to='employee_edu/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, default='Nome', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, default='Nome', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
