# Generated by Django 5.1.2 on 2025-02-03 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_employee_address_employee_city_employee_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employeelevel'),
        ),
    ]
