# Generated by Django 5.1.2 on 2025-02-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_jobdescription_jobrequirement_position_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='role',
        ),
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.ManyToManyField(blank=True, to='core.jobdescription'),
        ),
    ]
