# Generated by Django 5.1.2 on 2025-02-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_position_role_remove_position_description_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='position',
            name='unique_position_in_department',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='jobrequirement',
            name='name',
        ),
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
        migrations.RemoveField(
            model_name='position',
            name='requirement',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='core.position'),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
