# Generated by Django 5.1.2 on 2025-02-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_position_unique_position_in_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryincrementandpromotion',
            name='year',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
