# Generated by Django 5.1.2 on 2025-02-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_salaryincrementandpromotion_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryincrementandpromotion',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
