# Generated by Django 5.1.2 on 2025-02-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_leavetype_leaveapplication_employeeleavebalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(blank=True, choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('CASUAL', 'Casual Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('EARNED', 'Earned Leave'), ('COMPENSATORY', 'Compensatory Leave'), ('UNPAID', 'Unpaid Leave'), ('BEREAVEMENT', 'Bereavement Leave'), ('STUDY', 'Study Leave'), ('HALF-DAY', 'Half-Day Leave'), ('MARRIAGE', 'Marriage Leave'), ('SPECIAL', 'Special Leave')], max_length=50, null=True),
        ),
    ]
