# Generated by Django 5.1.2 on 2025-02-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_leavetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='allow_carry_forward',
            field=models.BooleanField(default=False, verbose_name='? is carry forwardable'),
        ),
    ]
