# Generated by Django 5.1.2 on 2025-02-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_leavetype_allow_carry_forward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='applied_no_days',
            new_name='applied_no_of_days',
        ),
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='approved_no_days',
            new_name='approved_no_of_days',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='accrual_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='accrues_monthly',
            field=models.BooleanField(default=False),
        ),
    ]
