# Generated by Django 5.1.2 on 2025-02-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_tenant'),
        ('core', '0062_alter_employeeleavebalance_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_user_profile', to='accounts.userprofile'),
        ),
    ]
