# Generated by Django 5.1.2 on 2025-02-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_employee_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavebalance',
            name='total_available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
