# Generated by Django 5.1.2 on 2025-02-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_employeeleavebalance_total_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavebalance',
            name='last_accrued_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
