# Generated by Django 5.1.2 on 2025-02-15 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_employeeleavebalance_last_accrued_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemodel',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LeaveBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leavetype')),
            ],
        ),
    ]
