# Generated by Django 5.1.2 on 2025-02-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='confirmation_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv_screening_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv_screening_status',
            field=models.CharField(blank=True, choices=[('SHORT-LISTED', 'Short Listed'), ('REJECTED', 'Rejected')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='exam_status',
            field=models.CharField(blank=True, choices=[('EXAM-PASS', 'Exam Pass'), ('EXAM-FAIL', 'Exam Fail')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='interview_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='interview_status',
            field=models.CharField(blank=True, choices=[('INTERVIEW-PASS', 'Interview Pass'), ('INTERVIEW-FAIL', 'Interview Fail')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='offer_status',
            field=models.CharField(blank=True, choices=[('offered', 'Offered'), ('waitlist', 'Waitlist')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='onboard_status',
            field=models.CharField(blank=True, choices=[('onboard', 'Onboard'), ('declined', 'Declined')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='approver_approval_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requester_approval_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='reviewer_approval_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Close')], default='SUBMITTED', max_length=100),
        ),
        migrations.AlterField(
            model_name='panel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
