# Generated by Django 5.1.2 on 2025-01-24 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_candidate_email_alter_job_job_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_exam', to='recruitment.job'),
        ),
    ]
