# Generated by Django 5.1.2 on 2025-01-24 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_candidate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeexam',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='recruitment.exam'),
        ),
    ]
