# Generated by Django 5.1.2 on 2025-01-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_takeexam_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AreaOfExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_experience', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_awarded', models.CharField(choices=[('Phd', 'Phd'), ('Bachelor', 'Bachelor')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_experience', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='total_score',
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv_screening_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='exam_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.age'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='area_of_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.areaofexperience'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.certification'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.education'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='institution_of_education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.educationalinstitution'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='subject_of_education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.educationalsubject'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.experience'),
        ),
        migrations.CreateModel(
            name='LanguageSkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('average', 'Average'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=40)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_levels', to='recruitment.language')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='language_skill_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.languageskilllevel'),
        ),
        migrations.AddField(
            model_name='language',
            name='score_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_language', to='recruitment.scorecard'),
        ),
        migrations.AddField(
            model_name='experience',
            name='score_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_experience', to='recruitment.scorecard'),
        ),
        migrations.AddField(
            model_name='educationalsubject',
            name='score_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_esubject', to='recruitment.scorecard'),
        ),
        migrations.AddField(
            model_name='educationalinstitution',
            name='score_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_institution', to='recruitment.scorecard'),
        ),
        migrations.AddField(
            model_name='education',
            name='score_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_education', to='recruitment.scorecard'),
        ),
        migrations.AddField(
            model_name='certification',
            name='score_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_certification', to='recruitment.scorecard'),
        ),
        migrations.AddField(
            model_name='areaofexperience',
            name='score_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_experience_area', to='recruitment.scorecard'),
        ),
        migrations.AddField(
            model_name='age',
            name='score_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_age', to='recruitment.scorecard'),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('score_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_skills', to='recruitment.scorecard')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.skills'),
        ),
    ]
