# Generated by Django 5.1.2 on 2025-01-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_age_areaofexperience_certification_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('SELECTED', 'Selected')], default='Applied', max_length=50),
        ),
    ]
