# Generated by Django 5.1.2 on 2025-01-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_age_created_at_age_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='language_skill_level',
        ),
        migrations.AddField(
            model_name='candidate',
            name='language_skill_level',
            field=models.ManyToManyField(blank=True, null=True, related_name='candidates', to='recruitment.languageskilllevel'),
        ),
    ]
