# Generated by Django 5.1.2 on 2025-01-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_remove_candidate_language_skill_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='language_skill_level',
            field=models.ManyToManyField(related_name='candidates', to='recruitment.languageskilllevel'),
        ),
    ]
