# Generated by Django 5.1.2 on 2025-01-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_alter_candidate_language_skill_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='user',
            new_name='candidate',
        ),
    ]
