# Generated by Django 5.1.2 on 2025-01-24 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_rename_user_candidate_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageskilllevel',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_skills', to='recruitment.candidate'),
        ),
    ]
