# Generated by Django 5.1.2 on 2025-01-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_languageskilllevel_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languageskilllevel',
            name='candidate',
        ),
    ]
