# Generated by Django 5.1.2 on 2025-01-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_remove_languageskilllevel_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='area_of_experience',
        ),
        migrations.AddField(
            model_name='experience',
            name='area_of_experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='education',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='institution_of_education',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='language_skill_level',
            field=models.ManyToManyField(to='recruitment.languageskilllevel'),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='subject_of_education',
        ),
        migrations.DeleteModel(
            name='AreaOfExperience',
        ),
        migrations.AddField(
            model_name='candidate',
            name='certification',
            field=models.ManyToManyField(to='recruitment.certification'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.ManyToManyField(to='recruitment.education'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.ManyToManyField(to='recruitment.experience'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='institution_of_education',
            field=models.ManyToManyField(to='recruitment.educationalinstitution'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(to='recruitment.skills'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='subject_of_education',
            field=models.ManyToManyField(to='recruitment.educationalsubject'),
        ),
    ]
