# Generated by Django 5.1.2 on 2025-01-24 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_remove_candidate_area_of_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='score_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.scorecard'),
        ),
    ]
