# Generated by Django 5.1.2 on 2025-01-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_job_score_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='pass_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='takeexam',
            name='obtained_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='takeexam',
            name='status',
            field=models.CharField(choices=[('APPeared', 'Appeared'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='Appeared', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SHORT-LISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('Exam-PASS', 'Exam Pass'), ('EXAM-FAIL', 'Exam Fail'), ('SELECTED', 'Selected'), ('ONBOARD', 'Onboard')], default='Applied', max_length=50),
        ),
    ]
