# Generated by Django 5.1.2 on 2025-01-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_alter_candidate_applied_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='certification',
            field=models.ManyToManyField(blank=True, to='recruitment.certification'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.ManyToManyField(blank=True, to='recruitment.education'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.ManyToManyField(blank=True, to='recruitment.experience'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='institution_of_education',
            field=models.ManyToManyField(blank=True, to='recruitment.educationalinstitution'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='language_skill_level',
            field=models.ManyToManyField(blank=True, to='recruitment.languageskilllevel'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(blank=True, to='recruitment.skills'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='subject_of_education',
            field=models.ManyToManyField(blank=True, to='recruitment.educationalsubject'),
        ),
    ]
