# Generated by Django 5.1.2 on 2025-01-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0021_remove_exam_name_exam_is_active_job_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatescreeninghistory',
            name='screening_round',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
