# Generated by Django 5.1.2 on 2025-01-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0023_interview_panelmember_interviewscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewscore',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
