# Generated by Django 5.1.2 on 2025-01-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0025_candidate_interview_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewscore',
            old_name='score',
            new_name='communication_skill_score',
        ),
        migrations.AddField(
            model_name='interviewscore',
            name='interpersonal_skill_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='interviewscore',
            name='managerial_skill_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='interviewscore',
            name='problem_solving_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='interviewscore',
            name='technical_skill_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
