# Generated by Django 5.1.2 on 2025-01-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0030_candidate_cv_screening_status_candidate_exam_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewscore',
            name='status',
            field=models.CharField(choices=[('INTERVIEW-PASS', 'Pass'), ('INTERVIEW-FAIL', 'Fail'), ('INTERVIEW-APPEARED', 'Appeared')], default='Appeared', max_length=50),
        ),
        migrations.AlterField(
            model_name='takeexam',
            name='status',
            field=models.CharField(choices=[('APPEARED', 'Appeared'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='Appeared', max_length=50),
        ),
    ]
