# Generated by Django 5.1.2 on 2025-01-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0031_interviewscore_status_alter_takeexam_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SHORT-LISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('Exam-PASS', 'Exam Pass'), ('EXAM-FAIL', 'Exam Fail'), ('SELECTED', 'Selected'), ('WAITING-IN-LIST', 'Wait in list'), ('ONBOARD', 'Onboard')], default='Applied', max_length=50),
        ),
    ]
