# Generated by Django 5.1.2 on 2025-01-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0032_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewscore',
            name='status',
            field=models.CharField(blank=True, choices=[('INTERVIEW-PASS', 'Pass'), ('INTERVIEW-FAIL', 'Fail'), ('INTERVIEW-APPEARED', 'Appeared')], default='Appeared', max_length=50, null=True),
        ),
    ]
