# Generated by Django 5.1.2 on 2025-01-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0033_alter_interviewscore_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('APPLIED', 'Applied'), ('SHORT-LISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('Exam-PASS', 'Exam Pass'), ('EXAM-FAIL', 'Exam Fail'), ('SELECTED', 'Selected'), ('WAITING-IN-LIST', 'Wait in list'), ('ONBOARD', 'Onboard')], default='Applied', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interviewscore',
            name='status',
            field=models.CharField(blank=True, choices=[('INTERVIEW-PASS', 'Pass'), ('INTERVIEW-FAIL', 'Fail'), ('INTERVIEW-APPEARED', 'Appeared')], default='INTERVIEW-APPEARED', max_length=50, null=True),
        ),
    ]
