# Generated by Django 5.1.2 on 2025-01-28 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0036_project_job_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
