# Generated by Django 5.1.2 on 2025-01-30 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_policiesandguideline'),
        ('recruitment', '0039_remove_job_salary_job_basic_salary_job_gross_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='joining_date',
        ),
        migrations.AddField(
            model_name='candidate',
            name='confirmation_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='confirmation_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined')], default='declined', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='joining_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='offer_status',
            field=models.CharField(choices=[('offered', 'Offered'), ('waitlist', 'Waitlist')], default='waitlist', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='onboard_status',
            field=models.CharField(choices=[('onboard', 'Onboard'), ('declined', 'Declined')], default='declined', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AddField(
            model_name='job',
            name='no_of_vacancies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('APPLIED', 'Applied'), ('SHORT-LISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('Exam-PASS', 'Exam Pass'), ('EXAM-FAIL', 'Exam Fail'), ('SELECTED', 'Selected'), ('OFFER-DECLINED', 'offer Declining'), ('WAIT-IN-LIST', 'Wait in list'), ('ONBOARD', 'Onboard')], default='Applied', max_length=50, null=True),
        ),
    ]
