# Generated by Django 5.1.2 on 2025-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0040_remove_job_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='confirmation_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='offer_status',
            field=models.CharField(blank=True, choices=[('offered', 'Offered'), ('waitlist', 'Waitlist')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='onboard_status',
            field=models.CharField(blank=True, choices=[('onboard', 'Onboard'), ('declined', 'Declined')], max_length=20, null=True),
        ),
    ]
