# Generated by Django 5.1.2 on 2025-01-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0041_alter_candidate_confirmation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='offer_status',
            field=models.CharField(blank=True, choices=[('offered', 'Offered'), ('waitlist', 'Waitlist'), ('accepted', 'Accepted'), ('declined', 'Declined')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
