# Generated by Django 5.1.2 on 2025-01-31 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_company_email_company_phone'),
        ('recruitment', '0042_alter_candidate_offer_status_alter_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_position', to='core.position'),
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_department', to='core.department'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_salary_structure', to='core.salarystructure'),
        ),
        migrations.AlterField(
            model_name='job',
            name='score_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.scorecard'),
        ),
    ]
