# Generated by Django 5.1.2 on 2025-01-31 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_company_email_company_phone'),
        ('recruitment', '0043_job_position_alter_job_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_location', to='core.location'),
        ),
    ]
