# Generated by Django 5.1.2 on 2025-01-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0044_job_location2_alter_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location2',
        ),
    ]
