# Generated by Django 5.1.2 on 2025-01-31 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_company_email_company_phone'),
        ('recruitment', '0046_candidate_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_joining_deadline_committed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='manager_confirmation_of_joining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
    ]
