# Generated by Django 5.1.2 on 2025-02-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0049_candidatedocument_commondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelmember',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
