# Generated by Django 5.1.2 on 2025-02-01 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0053_panel_is_active_panel_user_panelmember_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelmember',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='panelmember',
            name='job',
        ),
        migrations.AddField(
            model_name='panel',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_panel', to='recruitment.exam'),
        ),
        migrations.AddField(
            model_name='panel',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_panel', to='recruitment.job'),
        ),
    ]
