# Generated by Django 5.1.2 on 2025-02-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0054_remove_panelmember_exam_remove_panelmember_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='job',
        ),
        migrations.RemoveField(
            model_name='panelmember',
            name='panel',
        ),
        migrations.AddField(
            model_name='panel',
            name='exam',
            field=models.ManyToManyField(blank=True, to='recruitment.exam'),
        ),
        migrations.AddField(
            model_name='panel',
            name='job',
            field=models.ManyToManyField(blank=True, to='recruitment.job'),
        ),
        migrations.AddField(
            model_name='panelmember',
            name='panel',
            field=models.ManyToManyField(blank=True, to='recruitment.panel'),
        ),
    ]
