# Generated by Django 5.1.2 on 2025-02-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0055_remove_panel_exam_remove_panel_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='exam',
            field=models.ManyToManyField(blank=True, related_name='exam_panel', to='recruitment.exam'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='job_panel', to='recruitment.job'),
        ),
        migrations.AlterField(
            model_name='panelmember',
            name='panel',
            field=models.ManyToManyField(blank=True, related_name='panel_member_panel', to='recruitment.panel'),
        ),
    ]
