# Generated by Django 5.1.2 on 2025-02-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0056_alter_panel_exam_alter_panel_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='gross_salary',
        ),
    ]
