# Generated by Django 5.1.2 on 2025-02-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0057_remove_job_basic_salary_remove_job_gross_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='offer_status',
            field=models.CharField(blank=True, choices=[('offered', 'Offered'), ('waitlist', 'Waitlist')], max_length=20, null=True),
        ),
    ]
