# Generated by Django 5.1.2 on 2025-02-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0058_alter_candidate_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('APPLIED', 'Applied'), ('SHORT-LISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('Exam-PASS', 'Exam Pass'), ('EXAM-FAIL', 'Exam Fail'), ('SELECTED', 'Selected')], default='Applied', max_length=50, null=True),
        ),
    ]
