# Generated by Django 5.1.2 on 2025-02-03 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_jobdescription_jobrequirement_position_requirement'),
        ('recruitment', '0060_jobcategory_job_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, help_text='Please write reporting manager or hiring manager name', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
    ]
