# Generated by Django 5.1.2 on 2025-02-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0061_alter_job_reporting_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
    ]
