# Generated by Django 5.1.2 on 2025-02-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0062_remove_job_description_remove_job_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='pp_photo',
            field=models.FileField(blank=True, null=True, upload_to='Candidate_photo/'),
        ),
    ]
