# Generated by Django 5.1.2 on 2024-11-09 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('logistics', '0006_alter_purchasedispatchitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchaseinvoice',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='historicalpurchaseinvoice',
            name='purchase_shipment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.purchaseshipment'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_invoices', to='logistics.purchaseshipment'),
        ),
    ]
