# Generated by Django 5.1.2 on 2024-11-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_historicalpurchaseinvoice_purchase_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseinvoice',
            name='issued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='issued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
