# Generated by Django 5.1.2 on 2024-11-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_historicalpurchaseinvoice_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepayment',
            name='sale_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_payment_invoice', to='finance.saleinvoice'),
        ),
    ]
