# Generated by Django 5.1.2 on 2024-11-11 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_salepayment_sale_invoice'),
        ('logistics', '0007_alter_saledispatchschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsaleinvoice',
            name='sale_order',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='sale_order',
        ),
        migrations.AddField(
            model_name='historicalsaleinvoice',
            name='sale_shipment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.purchaseshipment'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='sale_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_shipment_invoices', to='logistics.purchaseshipment'),
        ),
    ]
