# Generated by Django 5.1.2 on 2024-11-11 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_historicalsaleinvoice_sale_order_and_more'),
        ('logistics', '0008_alter_saleshipment_sales_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaleinvoice',
            name='sale_shipment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.saleshipment'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='sale_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_shipment_invoices', to='logistics.saleshipment'),
        ),
    ]
