# Generated by Django 5.1.2 on 2024-11-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_historicalsaleinvoice_sale_shipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('PAYMEN_RECEIVED', 'Payment received')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalsalepayment',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('PAYMENT_DONE', 'Payment done')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('PAYMEN_RECEIVED', 'Payment received')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('PAYMENT_DONE', 'Payment done')], max_length=20, null=True),
        ),
    ]
