# Generated by Django 5.1.2 on 2024-11-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_historicalsaleinvoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('FULLY_PAID', 'Fully Paid'), ('PARTIALLY_PAID', 'Partially Paid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpurchasepayment',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('FULLY_PAID', 'Fully Paid'), ('PARTIALLY_PAID', 'Partially Paid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsaleinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('FULLY_PAID', 'Fully Paid'), ('PARTIALLY_PAID', 'Partially Paid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsalepayment',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'IN Process'), ('FULLY_PAID', 'Fully Paid'), ('PARTIALLY_PAID', 'Partially Paid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('FULLY_PAID', 'Fully Paid'), ('PARTIALLY_PAID', 'Partially Paid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('FULLY_PAID', 'Fully Paid'), ('PARTIALLY_PAID', 'Partially Paid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('FULLY_PAID', 'Fully Paid'), ('PARTIALLY_PAID', 'Partially Paid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'IN Process'), ('FULLY_PAID', 'Fully Paid'), ('PARTIALLY_PAID', 'Partially Paid')], max_length=20, null=True),
        ),
    ]
