# Generated by Django 5.1.2 on 2025-01-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'permissions': [('can_request_purchase_order', 'can request purchase_order'), ('can_review_purchase_order', 'can review purchase_order'), ('can_approve_purchase_order', 'can approve purchase order')]},
        ),
    ]
