# Generated by Django 5.1.2 on 2024-11-09 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_purchasedispatchitem_status'),
        ('purchase', '0003_alter_historicalpurchaseorderitem_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalqualitycontrol',
            name='purchase_order_item',
        ),
        migrations.RemoveField(
            model_name='qualitycontrol',
            name='purchase_order_item',
        ),
        migrations.AddField(
            model_name='historicalqualitycontrol',
            name='purchase_dispatch_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.purchasedispatchitem'),
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='purchase_dispatch_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_control', to='logistics.purchasedispatchitem'),
        ),
    ]
