# Generated by Django 5.1.2 on 2025-01-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchaseorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'permissions': [('can_request', 'can request'), ('can_review', 'Can review'), ('can_approve', 'Can approve')]},
        ),
    ]
