# Generated by Django 5.1.2 on 2025-02-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_batch_remaining_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
