# Generated by Django 5.1.2 on 2024-11-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_remove_historicalqualitycontrol_purchase_order_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalqualitycontrol',
            old_name='purchase_dispatch_item',
            new_name='purchase_order_item',
        ),
        migrations.RenameField(
            model_name='qualitycontrol',
            old_name='purchase_dispatch_item',
            new_name='purchase_order_item',
        ),
    ]
