# Generated by Django 5.1.2 on 2024-11-09 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_rename_purchase_order_item_historicalqualitycontrol_purchase_dispatch_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_request_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_request_order', to='purchase.purchaserequestorder'),
        ),
    ]
