# Generated by Django 5.1.2 on 2024-11-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_alter_historicalpurchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('ON_BOARD', 'On Board'), ('IN_TRANSIT', 'In Transit'), ('REACHED', 'Reached'), ('IN_CUSTOM', 'In Custom'), ('OBI', 'OBI'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='IN_PROCESS', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('ON_BOARD', 'On Board'), ('IN_TRANSIT', 'In Transit'), ('REACHED', 'Reached'), ('IN_CUSTOM', 'In Custom'), ('OBI', 'OBI'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='IN_PROCESS', max_length=30, null=True),
        ),
    ]
