# Generated by Django 5.1.2 on 2024-11-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_alter_historicalpurchaseorderitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaserequestorder',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_PROCESS', 'In Process'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequestorder',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_PROCESS', 'In Process'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20),
        ),
    ]
