# Generated by Django 5.1.2 on 2024-11-14 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_alter_historicalpurchaserequestorder_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequestorder',
            options={'permissions': [('can_request_purchase_order', 'Can create and submit purchase request'), ('can_review_purchase_order', 'Can review purchase request'), ('can_approve_purchase_order', 'Can approve purchase request')]},
        ),
        migrations.AddField(
            model_name='historicalpurchaserequestorder',
            name='approver',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequestorder',
            name='requester',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequestorder',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_orders_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_orders_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_orders_reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
