# Generated by Django 5.1.2 on 2024-11-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaserequestorder',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('IN_PROCESS', 'In Process'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpurchaserequestorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestorder',
            name='status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('IN_PROCESS', 'In Process'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
