# Generated by Django 5.1.2 on 2024-11-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_alter_historicalpurchaserequestorder_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequestorder',
            options={'permissions': [('can_request_purchase_order', 'can_request_purchase_order'), ('can_review_purchase_order', 'Can_review_purchase_order'), ('can_approve_purchase_order', 'Can_approve_purchase_order')]},
        ),
    ]
