# Generated by Django 5.1.2 on 2024-11-15 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0014_alter_purchaserequestorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequestorder',
            options={'permissions': [('can_request_purchase_order', 'can request purchaseo rder'), ('can_review_purchase_order', 'Can review purchase order'), ('can_approve_purchase_order', 'Can approve purchase order')]},
        ),
    ]
