# Generated by Django 5.1.2 on 2024-11-15 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_alter_purchaserequestorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'permissions': [('can_submit_purchase_order', 'Can submit purchase order'), ('can_review_purchase_order', 'Can review purchase order'), ('can_approve_purchase_order', 'Can approve purchase order')]},
        ),
        migrations.AlterModelOptions(
            name='purchaserequestorder',
            options={'permissions': [('can_submit_purchase_request_order', 'can submit purchase request order'), ('can_review_purchase_request_order', 'Can review purchase request order'), ('can_approve_purchase_equest_order', 'Can approve purchase request order')]},
        ),
    ]
