# Generated by Django 5.1.2 on 2024-11-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'permissions': [('can_request', 'can request'), ('can_review', 'Can review'), ('can_approve', 'Can approve')]},
        ),
        migrations.AlterModelOptions(
            name='purchaserequestorder',
            options={'permissions': [('can_request', 'can request'), ('can_review', 'Can review'), ('can_approve', 'Can approve')]},
        ),
    ]
