# Generated by Django 5.1.2 on 2024-11-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0019_historicalpurchaseorder_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaserequestorder',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('SUBMISSION_DONE', 'Submission done'), ('REVIEW_DONE', 'Review done'), ('APPROVAL_DONE', 'Approval_done'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('SUBMISSION_DONE', 'Submission done'), ('REVIEW_DONE', 'Review done'), ('APPROVAL_DONE', 'Approval_done'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpurchaserequestorder',
            name='status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Created'), ('IN_PROCESS', 'In Process'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestorder',
            name='status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Created'), ('IN_PROCESS', 'In Process'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
    ]
