# Generated by Django 5.1.2 on 2024-11-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0020_historicalpurchaserequestorder_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('SUBMISSION_DONE', 'Submission done'), ('REVIEW_DONE', 'Review done'), ('APPROVAL_DONE', 'Approval_done'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('SUBMISSION_DONE', 'Submission done'), ('REVIEW_DONE', 'Review done'), ('APPROVAL_DONE', 'Approval_done'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
    ]
