# Generated by Django 5.1.2 on 2024-11-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0022_historicalpurchaseorder_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpurchaserequestorder',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestorder',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20, null=True),
        ),
    ]
