# Generated by Django 5.1.2 on 2024-11-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0023_alter_historicalpurchaseorder_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='approval_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approval_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
