# Generated by Django 5.1.2 on 2024-11-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0024_historicalpurchaseorder_approval_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='approval_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='approval_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
