# Generated by Django 5.1.2 on 2024-11-16 02:21

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0025_alter_historicalpurchaseorder_approval_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='approver_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='requester_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='reviewer_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approver_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requester_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='reviewer_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
