# Generated by Django 5.1.2 on 2024-11-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0028_historicalpurchaseorder_approver_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaserequestorder',
            name='Approver_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequestorder',
            name='Requester_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequestorder',
            name='Reviewer_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequestorder',
            name='approval_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequestorder',
            name='approver_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequestorder',
            name='requester_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchaserequestorder',
            name='reviewer_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='Approver_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='Requester_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='Reviewer_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='approval_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='approver_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='requester_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestorder',
            name='reviewer_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
