# Generated by Django 5.1.2 on 2024-12-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TenantApplication',
            new_name='TenantData',
        ),
    ]
