# Generated by Django 5.1.2 on 2025-01-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_tenantapplication_tenantdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdata',
            name='subscription_period',
            field=models.CharField(blank=True, choices=[('6-MONTHS', '6 months'), ('1-YEAR', '1 year'), ('18-MONTHS', '18 Months'), ('2-YEARS', '2 Years'), ('3-YEARS', '3 Years'), ('4-YEARS', '4 Years'), ('5-YEARS', '5 Years')], max_length=30, null=True),
        ),
    ]
