# Generated by Django 5.1.2 on 2024-12-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_tenantapplication_tenantinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='tenantapplication',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantapplication',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='clients.client'),
        ),
    ]
