# Generated by Django 5.1.2 on 2024-12-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_created_on_client_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantapplication',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='active', max_length=10),
        ),
    ]
