# Generated by Django 5.1.2 on 2025-01-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_tenantdata_subscription_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdata',
            name='subscription_period',
            field=models.PositiveIntegerField(blank=True, choices=[(6, '6 Months'), (12, '1 Year'), (24, '2 Years'), (36, '3 Years'), (48, '4 Years'), (60, '5 Years')], null=True, unique=True),
        ),
    ]
