# Generated by Django 5.1.2 on 2025-01-08 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_tenantdata_subscription_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(choices=[(6, '6 Months'), (12, '1 Year'), (24, '2 Years'), (36, '3 Years'), (48, '4 Years'), (60, '5 Years')], unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('features', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tenantdata',
            name='subscription_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.subscriptionplan', unique=True),
        ),
    ]
