# Generated by Django 5.1.2 on 2025-01-08 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdata',
            name='subscription_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.subscriptionplan'),
        ),
    ]
