# Generated by Django 5.1.2 on 2025-01-08 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_subscriptionplan_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='clients.client'),
        ),
    ]
