# Generated by Django 5.1.2 on 2025-01-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_tenant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprofile',
            name='card_brand',
            field=models.CharField(blank=True, choices=[('VISA', 'Visa'), ('MASTER-CARD', 'Master card'), ('AMEX', 'American Express')], max_length=50, null=True),
        ),
    ]
