# Generated by Django 5.1.2 on 2025-02-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_paymentprofile_card_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.PositiveIntegerField(choices=[(1, '30 days free trial'), (6, '6 Months'), (12, '1 Year'), (24, '2 Years'), (36, '3 Years'), (48, '4 Years'), (60, '5 Years')], unique=True),
        ),
    ]
