# Generated by Django 5.1.2 on 2025-02-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_demorequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(help_text='subdomain could be your company name or nay name you prefer', max_length=100, unique=True),
        ),
    ]
