# Generated by Django 5.1.2 on 2025-02-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_tenant_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_trial_used',
            field=models.BooleanField(default=False),
        ),
    ]
