# Generated by Django 5.1.2 on 2025-02-17 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_tenant_ip_address_tenant_is_trial_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprofile',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_payment_profile', to='clients.tenant'),
        ),
    ]
