# Generated by Django 5.1.2 on 2025-02-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_paymentprofile_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='registered_tenant',
            field=models.BooleanField(default=False),
        ),
    ]
