# Generated by Django 5.1.2 on 2025-02-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_client_registered_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
