# Generated by Django 5.1.2 on 2025-01-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('PURCHASE-NOTIFICATION', 'Purchase notification'), ('SALES-NOTIFICATION', 'Sales Notification'), ('PRODUCTION-NOTIFICATION', 'Production notification'), ('GENERAL-NOTIFICATION', 'General Notification')], max_length=50, null=True),
        ),
    ]
