# Generated by Django 5.1.2 on 2025-01-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('PURCHASE-NOTIFICATION', 'Purchase notification'), ('SALES-NOTIFICATION', 'Sales Notification'), ('PRODUCTION-NOTIFICATION', 'Production notification'), ('GENERAL-NOTIFICATION', 'General Notification'), ('SHIPMENT-NOTIFICATION', 'Shipment Notification'), ('RETURN-NOTIFICATION', 'Return Notification'), ('APPRAISAL-NOTIFICATION', 'Appraisal Notification'), ('OPERATIONS-NOTIFICATION', 'Appraisal Notification'), ('TICKET-NOTIFICATION', 'Ticket Notification'), ('TASK-NOTIFICATION', 'Task Notification')], max_length=50, null=True),
        ),
    ]
