# Generated by Django 5.1.2 on 2025-02-19 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('manufacture', '0001_initial'),
        ('operations', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='existing_items_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Existing_items_inventory', to='operations.existingorder'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='inventory_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transaction', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='manufacture_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacure_inventory', to='manufacture.materialsrequestorder'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='operations_request_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_request_order_inventory', to='operations.operationsrequestorder'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
