# Generated by Django 5.1.2 on 2025-02-19 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('product', '0001_initial'),
        ('purchase', '0001_initial'),
        ('repairreturn', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_transactions', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_transactions', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='scrapped_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrapped_order_inventory', to='repairreturn.scrappedorder'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transaction_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_inventory', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='reorderlevel',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reorder_location', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='reorderlevel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reorder_levels', to='product.product'),
        ),
        migrations.AddField(
            model_name='reorderlevel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reorder_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_locations', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='target_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_locations', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='transfer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='inventory.transferorder'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_transfers', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='target_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_transfers', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='reorderlevel',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reorder_warehouse', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventory', to='inventory.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='reorderlevel',
            unique_together={('product', 'warehouse')},
        ),
    ]
