# Generated by Django 5.1.2 on 2024-11-09 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transaction', to='inventory.inventorytransaction'),
        ),
    ]
