# Generated by Django 5.1.2 on 2024-11-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_transferorder_transferitem_reorderlevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferitem',
            name='product_type',
        ),
    ]
