# Generated by Django 5.1.2 on 2024-12-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventory_inventory_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='inventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transaction', to='inventory.inventorytransaction'),
        ),
    ]
