# Generated by Django 5.1.2 on 2024-11-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_transferitem_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventory',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
