# Generated by Django 5.1.2 on 2024-11-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_historicalinventory_quantity_inventory_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalInventory',
        ),
    ]
