# Generated by Django 5.1.2 on 2024-11-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_delete_historicalinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventorytransaction',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
