# Generated by Django 5.1.2 on 2024-11-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_historicalinventorytransaction_remarks_and_more'),
        ('manufacture', '0006_rename_historicalqualitycontrol_historicalmanufacturequalitycontrol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventorytransaction',
            name='manufacture_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manufacture.materialsrequestorder'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='manufacture_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacure_inventory', to='manufacture.materialsrequestorder'),
        ),
    ]
