# Generated by Django 5.1.2 on 2024-12-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_inventorytransaction_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
