# Generated by Django 5.1.2 on 2024-12-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorytransaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
