# Generated by Django 5.1.2 on 2024-12-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_department_team_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='extension_approval',
            new_name='extension_approval_status',
        ),
    ]
