# Generated by Django 5.1.2 on 2024-12-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_extension_approval_task_extension_approval_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='extended_due_date',
            new_name='extended_due_datetime',
        ),
    ]
