# Generated by Django 5.1.2 on 2024-12-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_extension_approval_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_extension_approval_status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=30, null=True),
        ),
    ]
