# Generated by Django 5.1.2 on 2024-12-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_time_extension_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeextensionrequest',
            name='time_extension_reason',
            field=models.CharField(blank=True, choices=[('INTERNAL_AFFAIR', 'Internal Affair'), ('EXTERNAL_AFFAIR', 'External affair'), ('LOGISTICS_AFFAIR', 'Logistics affair'), ('FINANCIAL_AFFAIR', 'Financial affair'), ('LABOR_CRISIS', 'Labor crisis'), ('BAD_WEATHER', 'Bad weather'), ('OTHER_DEPARTMENT_DEPENDENCY', 'Other department dependency')], max_length=50, null=True),
        ),
    ]
