# Generated by Django 5.1.2 on 2024-12-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_timeextensionrequest_time_extension_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeextensionrequest',
            name='requested_extension_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
