# Generated by Django 5.1.2 on 2024-12-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_timeextensionrequest_requested_extension_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeextensionrequest',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_extension_requests', to='tasks.task'),
        ),
    ]
