# Generated by Django 5.1.2 on 2024-12-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_taskmessage_delete_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='original_obtained_number',
            new_name='manager_given_number',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='original_obtained_score',
            new_name='manager_given_score',
        ),
    ]
