# Generated by Django 5.1.2 on 2024-12-24 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_rename_manager_given_quantitative_number_performanceevaluation_given_quantitative_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeextensionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeextensionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
