# Generated by Django 5.1.2 on 2024-12-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_performanceevaluation_evaluator'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceevaluation',
            name='half_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
