# Generated by Django 5.1.2 on 2025-01-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_teammember_is_team_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='is_team_leader',
            field=models.BooleanField(default=False),
        ),
    ]
