# Generated by Django 5.1.2 on 2025-01-09 11:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='manufacture',
            new_name='production',
        ),
        migrations.AddField(
            model_name='task',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_origin_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_resolution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('SALES', 'sales'), ('OPERATIONS', 'Operation'), ('PRODUCTION', 'production'), ('FINANCE', 'finance'), ('BILLING', 'Billing'), ('TECHNICAL', 'Technical')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
