# Generated by Django 5.1.2 on 2025-01-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_rename_manufacture_ticket_production_task_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('SALES', 'Sales'), ('OPERATIONS', 'Operation'), ('PRODUCTION', 'Production'), ('FINANCE', 'Finance'), ('BILLING', 'Billing'), ('TECHNICAL', 'Technical'), ('IT', 'IT'), ('GENERAL', 'General')], max_length=50, null=True),
        ),
    ]
