# Generated by Django 5.1.2 on 2025-01-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_alter_ticket_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(editable=False, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('SALES', 'Sales'), ('OPERATIONS', 'Operation'), ('PRODUCTION', 'Production'), ('FINANCE', 'Finance'), ('BILLING', 'Billing'), ('TECHNICAL', 'Technical'), ('IT', 'IT'), ('GENERAL', 'General')], max_length=150, null=True),
        ),
    ]
