# Generated by Django 5.1.2 on 2025-01-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_feedback',
            field=models.CharField(blank=True, choices=[('SOLVED', 'Solved'), ('NOT_SOLVED', 'Not Solved'), ('PROGRESS-20%', 'Progress 20%'), ('PROGRESS-40%', 'Progress 20%'), ('PROGRESS-50%', 'Progress 30%'), ('PROGRESS-70%', 'Progress 40%'), ('PROGRESS-80%', 'Progress 50%'), ('PROGRESS-100%', 'Progress 60%'), ('PROGRESS-50%', 'Progress 70%'), ('PROGRESS-70%', 'Progress 80%'), ('PROGRESS-80%', 'Progress 100%')], max_length=100, null=True),
        ),
    ]
