# Generated by Django 5.1.2 on 2025-01-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_alter_ticket_customer_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
