# Generated by Django 5.1.2 on 2025-01-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_ticket_customer_comments_ticket_user_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='customer_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
