# Generated by Django 5.1.2 on 2025-01-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_alter_ticket_customer_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='progress',
            new_name='progress_by_customer',
        ),
        migrations.AddField(
            model_name='ticket',
            name='progress_by_user',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
