# Generated by Django 5.1.2 on 2025-01-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_rename_progress_ticket_progress_by_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('TICKET', 'Ticket'), ('TASK', 'Task')], max_length=200, null=True),
        ),
    ]
