# Generated by Django 5.1.2 on 2025-01-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_taskmessagereadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='organization',
            field=models.CharField(blank=True, choices=[('ROBI', 'Robi'), ('GP', 'Gp'), ('BANGLALINK', 'Banglalink'), ('TELETALK', 'Teletalk'), ('INTERNAL', 'Internal')], max_length=100, null=True),
        ),
    ]
