# Generated by Django 5.1.2 on 2025-01-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantData',
        ),
        migrations.DeleteModel(
            name='TenantInfo',
        ),
    ]
