# Generated by Django 5.1.2 on 2025-02-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('IN-USE', 'In use'), ('PENALIZED', 'Penalized'), ('BOOKED', 'Booked'), ('FAULTY', 'Faulty'), ('COMPLETED', 'Completed')], max_length=50, null=True),
        ),
    ]
