# Generated by Django 5.1.2 on 2025-01-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_transport_vehicle_fuel_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='vehicle_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='vehicle_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
