# Generated by Django 5.1.2 on 2025-01-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_transport_vehicle_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='vehicle_brand_name',
            field=models.CharField(choices=[('toyota_pickup_single', 'toyota_pickup_single'), ('nissan_pickup_single', 'nissan_pickup_single'), ('tata_pickup_single', 'tata_pickup_single'), ('toyota_pickup_double', 'toyota_pickup_double'), ('nissan_pickup_double', 'nissan_pickup_double'), ('tata_pickup_double', 'tata_pickup_double'), ('toyota_private_car', 'toyota_private_car'), ('toyota_microbus', 'toyota_microbus'), ('PRIVAT-CAR', 'Private Car'), ('MICROBUS', 'Microbus'), ('BUS', 'Bus'), ('MINITRUCK', 'Mini Truck'), ('TRUCK', 'Truck')], default='None', max_length=50),
        ),
    ]
