# Generated by Django 5.1.2 on 2025-01-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_transport_vehicle_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportusage',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
