# Generated by Django 5.1.2 on 2025-01-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_alter_transport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportusage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='transportusage',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='transportusage',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='transportusage',
            name='start_time',
        ),
        migrations.AddField(
            model_name='transportusage',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportusage',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
