# Generated by Django 5.1.2 on 2025-01-14 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_alter_transportrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportusage',
            old_name='total_fuel_cost',
            new_name='fuel_cost',
        ),
    ]
