# Generated by Django 5.1.2 on 2025-01-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_rename_total_fuel_cost_transportusage_fuel_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinghistory',
            name='usage',
        ),
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN-USE', 'In use'), ('PENALIZED', 'Penalized'), ('BOOKED', 'Booked'), ('FAULTY', 'Faulty')], max_length=50),
        ),
    ]
