# Generated by Django 5.1.2 on 2025-01-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_remove_bookinghistory_usage_alter_transport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN-USE', 'In use'), ('PENALIZED', 'Penalized'), ('BOOKED', 'Booked'), ('FAULTY', 'Faulty')], default='AVAILABLE', max_length=50),
        ),
    ]
