# Generated by Django 5.1.2 on 2025-01-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_alter_transport_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportrequest',
            old_name='transport',
            new_name='vehicle',
        ),
    ]
