# Generated by Django 5.1.2 on 2025-01-14 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_rename_transport_transportrequest_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerapproval',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='managerapproval',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_approval', to='transport.transportrequest'),
        ),
    ]
