# Generated by Django 5.1.2 on 2025-01-14 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_managerapproval_status_alter_managerapproval_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerapproval',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_approval', to='transport.transportrequest'),
        ),
    ]
