# Generated by Django 5.1.2 on 2025-01-14 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_bookinghistory_created_at_bookinghistory_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='actual_return',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transportrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
