# Generated by Django 5.1.2 on 2025-01-15 02:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0017_transportrequest_actual_return_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRentalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_rent_paid_id', models.CharField(default='None', max_length=50)),
                ('vehicle_rent_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('vehicle_body_overtime_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('vehicle_driver_overtime_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('vehicle_kilometer_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('vehicle_total_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('comments', models.TextField(blank=True, default='None', max_length=50, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiclerent_info', to='transport.transport')),
            ],
        ),
    ]
