# Generated by Django 5.1.2 on 2025-01-15 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0018_vehiclerentalcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuelPumpPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_date', models.DateField(blank=True, default=None, null=True)),
                ('payment_id', models.CharField(blank=True, default='None', max_length=100, null=True)),
                ('payment_document', models.ImageField(blank=True, null=True, upload_to='fuel_pump_payment')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pump_pay_data', to='transport.fuelpumpdatabase')),
            ],
        ),
    ]
