# Generated by Django 5.1.2 on 2025-01-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0020_fuelpumppayment_paid_at_fuelpumppayment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedetails',
            name='insurance_document',
            field=models.ImageField(blank=True, null=True, upload_to='insurance_paper'),
        ),
        migrations.AddField(
            model_name='vehiclerentalcost',
            name='payment_document',
            field=models.ImageField(blank=True, null=True, upload_to='Vehicle_payment'),
        ),
    ]
