# Generated by Django 5.1.2 on 2025-01-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0021_insurancedetails_insurance_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelpumppayment',
            name='payment_date',
        ),
    ]
