# Generated by Django 5.1.2 on 2025-01-17 03:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0022_remove_fuelpumppayment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelpumppayment',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
