# Generated by Django 5.1.2 on 2025-01-17 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0023_alter_fuelpumppayment_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelrefill',
            name='paid_at',
        ),
    ]
