# Generated by Django 5.1.2 on 2025-01-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0024_remove_fuelrefill_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpumpdatabase',
            name='pump_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fuelrefill',
            name='refil_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='managerapproval',
            name='approval_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='request_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transportusage',
            name='transport_usage_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fuelrefill',
            unique_together={('vehicle', 'refil_code')},
        ),
    ]
