# Generated by Django 5.1.2 on 2025-01-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0025_fuelpumpdatabase_pump_code_fuelrefill_refil_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='vehicle_initial_mileage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
