# Generated by Django 5.1.2 on 2025-01-18 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0026_transport_vehicle_initial_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportusage',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_usage', to='transport.transportrequest'),
        ),
    ]
