# Generated by Django 5.1.2 on 2025-01-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0027_alter_transportrequest_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequest',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('Goods', 'Goods'), ('Staff', 'Staff')], max_length=10, null=True),
        ),
    ]
