# Generated by Django 5.1.2 on 2025-01-18 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0029_alter_transportrequest_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportextension',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_extension', to='transport.transportrequest'),
        ),
    ]
