# Generated by Django 5.1.2 on 2025-01-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0031_transportextension_approval_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportextension',
            old_name='approval_comment',
            new_name='calcellation_reason',
        ),
        migrations.AddField(
            model_name='transportextension',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], max_length=50, null=True),
        ),
    ]
