# Generated by Django 5.1.2 on 2025-01-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0032_rename_approval_comment_transportextension_calcellation_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportextension',
            old_name='calcellation_reason',
            new_name='cancellation_reason',
        ),
    ]
