# Generated by Django 5.1.2 on 2025-01-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0033_rename_calcellation_reason_transportextension_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportextension',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='PENDING', max_length=50),
        ),
    ]
