# Generated by Django 5.1.2 on 2025-01-19 01:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0034_alter_transportextension_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerapproval',
            name='approved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
