# Generated by Django 5.1.2 on 2025-01-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0035_alter_managerapproval_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportextension',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
