# Generated by Django 5.1.2 on 2025-01-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0036_alter_transportextension_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportextension',
            name='requested_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
