# Generated by Django 5.1.2 on 2025-01-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0037_transportextension_requested_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('IN-USE', 'In use'), ('PENALIZED', 'Penalized'), ('BOOKED', 'Booked'), ('FAULTY', 'Faulty')], max_length=50, null=True),
        ),
    ]
