# Generated by Django 5.1.2 on 2025-02-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0039_penaltypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
