# Generated by Django 5.1.2 on 2024-11-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsalequalitycontrol',
            old_name='sale_order_item',
            new_name='sale_dispatch_item',
        ),
        migrations.RenameField(
            model_name='salequalitycontrol',
            old_name='sale_order_item',
            new_name='sale_dispatch_item',
        ),
        migrations.AddField(
            model_name='historicalsaleorderitem',
            name='sale_request_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.salerequestitem'),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='sale_request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_request_item', to='sales.salerequestitem'),
        ),
    ]
