# Generated by Django 5.1.2 on 2025-02-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_batch_purchaseorderitem_batch'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerequestitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_sale_request_item', to='purchase.batch'),
        ),
        migrations.AddField(
            model_name='salerequestitem',
            name='unit_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
