# Generated by Django 5.1.2 on 2024-12-20 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleorder',
            options={'permissions': [('can_request', 'can request'), ('can_review', 'Can review'), ('can_approve', 'Can approve')]},
        ),
        migrations.AlterModelOptions(
            name='salerequestorder',
            options={'permissions': [('can_request', 'can request'), ('can_review', 'Can review'), ('can_approve', 'Can approve')]},
        ),
    ]
