# Generated by Django 5.1.2 on 2025-02-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_saleorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('READY_FOR_QC', 'Ready for QC'), ('DISPATCHED', 'Dispatched'), ('ON_BOARD', 'On Board'), ('IN_TRANSIT', 'In Transit'), ('CUSTOM_CLEARANCE_IN_PROCESS', 'Custom Clearance In Process'), ('REACHED', 'Reached'), ('OBI', 'OBI done'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='IN_PROCESS', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salerequestorder',
            name='status',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'In Process'), ('READY_FOR_QC', 'Ready for QC'), ('DISPATCHED', 'Dispatched'), ('ON_BOARD', 'On Board'), ('IN_TRANSIT', 'In Transit'), ('CUSTOM_CLEARANCE_IN_PROCESS', 'Custom Clearance In Process'), ('REACHED', 'Reached'), ('OBI', 'OBI done'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50, null=True),
        ),
    ]
