# Generated by Django 5.1.2 on 2024-11-11 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_alter_saleshipment_sales_order'),
        ('sales', '0002_rename_sale_order_item_historicalsalequalitycontrol_sale_dispatch_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsalequalitycontrol',
            name='sale_dispatch_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.saledispatchitem'),
        ),
        migrations.AlterField(
            model_name='salequalitycontrol',
            name='sale_dispatch_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_quality_control', to='logistics.saledispatchitem'),
        ),
    ]
