# Generated by Django 5.1.2 on 2025-02-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_saleorder_status_alter_salerequestorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salequalitycontrol',
            name='quality_check_by',
            field=models.CharField(blank=True, choices=[('BY-CUSTOMER', 'By Customer'), ('BY-EMPLOYEE', 'By Employee')], max_length=30, null=True),
        ),
    ]
