# Generated by Django 5.1.2 on 2024-11-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_historicalsalequalitycontrol_sale_dispatch_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROCESS', 'In Process'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='IN_PROCESS', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROCESS', 'In Process'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='IN_PROCESS', max_length=20, null=True),
        ),
    ]
