# Generated by Django 5.1.2 on 2025-02-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salequalitycontrol_quality_check_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='salequalitycontrol',
            name='bad_quantity_by_customer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salequalitycontrol',
            name='good_quantity_by_customer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
