# Generated by Django 5.1.2 on 2024-11-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_historicalsaleorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalequalitycontrol',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('done', 'done')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='salequalitycontrol',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('done', 'done')], max_length=15, null=True),
        ),
    ]
