# Generated by Django 5.1.2 on 2024-11-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_historicalsalequalitycontrol_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsalerequestorder',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROCESS', 'In Process'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salerequestorder',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROCESS', 'In Process'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, null=True),
        ),
    ]
