# Generated by Django 5.1.2 on 2025-02-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salequalitycontrol_bad_quantity_by_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salequalitycontrol',
            name='inspection_date_by_customer',
            field=models.DateField(blank=True, null=True),
        ),
    ]
