# Generated by Django 5.1.2 on 2025-02-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salequalitycontrol_inspection_date_by_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salequalitycontrol',
            name='comments_by_customer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
