# Generated by Django 5.1.2 on 2024-11-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_historicalsalerequestorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleorder',
            name='Approver_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='Requester_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='Reviewer_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='approval_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='approver_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='requester_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='reviewer_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalsalerequestorder',
            name='Approver_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsalerequestorder',
            name='Requester_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsalerequestorder',
            name='Reviewer_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsalerequestorder',
            name='approval_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='historicalsalerequestorder',
            name='approver_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalsalerequestorder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsalerequestorder',
            name='requester_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalsalerequestorder',
            name='reviewer_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='Approver_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='Requester_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='Reviewer_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='approval_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='approver_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='requester_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='reviewer_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='Approver_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='Requester_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='Reviewer_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='approval_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='approver_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='requester_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salerequestorder',
            name='reviewer_approval_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
