# Generated by Django 5.1.2 on 2024-11-17 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_historicalinventorytransaction_remarks_and_more'),
        ('sales', '0007_historicalsaleorder_approver_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleorder',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
